[workspace]
resolver = "2"
members = [
  "adafruit-featherwing-oled128x64",
  "sh1107",
]

[profile.release]
debug = 1
lto = false
codegen-units = 1
panic = "abort"
opt-level = 2

[patch.crates-io]
rp2040-hal = { git = "https://github.com/rp-rs/rp-hal" }
