[package]
name = "adafruit-featherwing-oled128x64"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sh1107 = { version = "*", path = "../sh1107" }
embedded-hal-async = "0.1.0-alpha.1"

[dev-dependencies]
cortex-m = "0.7.3"
cortex-m-rt = "0.7"

embedded-graphics = "*"
embedded-hal = { version = "1.0.0-alpha.8" }
nb = "*"

promicro-rp2040-boilerplate = { path = "../promicro-rp2040-boilerplate" }

nostd_async = { version = "0.6.0", features = ["cortex_m"] }

rtt-target = { version = "*", features = ["cortex-m"] }
