[package]
name = "adafruit-featherwing-oled128x64"
version = "0.1.0"
edition = "2021"
license = "Apache-2.0"
description = "Driver for Adafruit FeatherWing OLED 128x64 display"
homepage = "https://github.com/ithinuel/sh1107-rs"
repository = "https://github.com/ithinuel/sh1107-rs"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sh1107 = { version = "0.1.0", path = "../sh1107" }
embedded-hal-async = "0.1.0-alpha.1"
embedded-graphics = { version = "0.7.1", optional = true }
embedded-hal = { version = "1.0.0-alpha.8", optional = true }
itertools = { version = "0.10.3", default-features = false, optional = true }
arrayvec = { version =  "0.7.2", default-features = false, optional = true }
cfg-if = "1"

[dev-dependencies]
cortex-m = "0.7.6"
cortex-m-rt = "0.7"

embedded-hal = { version = "1.0.0-alpha.8" }

promicro-rp2040-boilerplate = { path = "../promicro-rp2040-boilerplate" }
pico-explorer-boilerplate = { path = "../pico-explorer-boilerplate" }
rpi-pico-boilerplate = { path = "../rpi-pico-boilerplate" }

nostd_async = { version = "0.6.0", features = ["cortex_m"] }
defmt = "0.3.2"
defmt-rtt = "0.3.2"

futures = { version = "0.3.24", default-features = false }

[features]
promicro = []
pico-explorer = []
rpi-pico = []
embedded-graphics = ["dep:embedded-graphics", "embedded-hal", "itertools", "arrayvec"]

[[example]]
name = "embedded-graphics"
required-features = ["embedded-graphics"]
