[package]
name = "promicro-rp2040-boilerplate"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
embedded-hal-async = "0.1.0-alpha.1"
futures = { version = "*", default-features = false }
rp2040-async-i2c = { git = "https://github.com/ithinuel/rp2040-async-i2c" }
sparkfun-pro-micro-rp2040 = "0.4.0"
sh1107 = { version = "*", path = "../sh1107" }
critical-section = "1.0.0"
fugit = "0.3.6"
panic-probe = "*"
defmt = "0.3.0"
